import os
import sys
import tempfile

import openpyxl

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "alerts"))

# pipeline/excel_writer.py is a different module that happens to share this
# exact filename - see the matching comment in test_excel_writer.py. Evict
# any stale entry so this test always gets alerts' version.
sys.modules.pop("excel_writer", None)

from excel_writer import COLUMNS, append_alert  # noqa: E402
from kafka_consumer import normalize_alert  # noqa: E402

FULL_ALERT = {
    "transaction_id": "txn-1",
    "terminal_id": "TRM00001",
    "merchant_id": "MRC0001",
    "card_bin": "539983",
    "fraud_probability": 0.91,
    "alert_tier": "critical",
    "state": "Lagos",
}


def _new_workbook(path: str) -> None:
    wb = openpyxl.Workbook()
    wb.active.append(COLUMNS)
    wb.save(path)


def test_normalize_alert_lowercases_ksqldb_uppercase_keys():
    # ksqlDB serializes JSON values keyed by its uppercased column names -
    # e.g. CREATE STREAM ... (TRANSACTION_ID STRING KEY, ALERT_TIER
    # STRING, ...) produces messages with those exact uppercase keys.
    raw = {
        "TRANSACTION_ID": "txn-1",
        "TERMINAL_ID": "TRM00001",
        "MERCHANT_ID": "MRC0001",
        "CARD_BIN": "539983",
        "FRAUD_PROBABILITY": 0.91,
        "ALERT_TIER": "critical",
        "STATE": "Lagos",
        "TERMINAL_NAME": "Ikeja Retail Counter 1",
        "MERCHANT_NAME": "Ikeja Fashion Emporium",
    }

    normalized = normalize_alert(raw)

    assert normalized["transaction_id"] == "txn-1"
    assert normalized["alert_tier"] == "critical"
    # Every column append_alert() actually writes must survive normalization.
    for col in COLUMNS:
        if col not in {"alert_id", "created_at"}:  # generated by append_alert itself
            assert col in normalized


def test_append_alert_does_not_raise_on_a_field_missing_from_the_message():
    # ksqlDB's JSON serializer omits a field entirely when its value is
    # NULL (e.g. merchant_id when 03_create_alert_stream.sql's LEFT JOIN
    # finds no matching reference row) rather than emitting it as null -
    # this is the exact shape of the first real alert this project ever
    # produced end to end, which crashed the whole consumer process with
    # KeyError before append_alert() switched to alert.get(col).
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "alerts.xlsx")
        _new_workbook(path)
        alert_missing_merchant_id = {k: v for k, v in FULL_ALERT.items() if k != "merchant_id"}

        append_alert(alert_missing_merchant_id, xlsx_path=path)

        ws = openpyxl.load_workbook(path).active
        row = next(ws.iter_rows(min_row=2, max_row=2, values_only=True))
        assert row[COLUMNS.index("transaction_id")] == "txn-1"
        assert row[COLUMNS.index("merchant_id")] is None


def test_append_alert_writes_every_column_when_all_fields_present():
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "alerts.xlsx")
        _new_workbook(path)

        append_alert(dict(FULL_ALERT), xlsx_path=path)

        ws = openpyxl.load_workbook(path).active
        row = next(ws.iter_rows(min_row=2, max_row=2, values_only=True))
        assert row[COLUMNS.index("merchant_id")] == "MRC0001"
        assert row[COLUMNS.index("alert_tier")] == "critical"
