import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "alerts"))

# pipeline/excel_writer.py is a different module that happens to share this
# exact filename - see the matching comment in test_excel_writer.py. Evict
# any stale entry so this test always gets alerts' version.
sys.modules.pop("excel_writer", None)

from excel_writer import COLUMNS  # noqa: E402
from kafka_consumer import normalize_alert  # noqa: E402


def test_normalize_alert_lowercases_ksqldb_uppercase_keys():
    # ksqlDB serializes JSON values keyed by its uppercased column names -
    # e.g. CREATE STREAM ... (TRANSACTION_ID STRING KEY, ALERT_TIER
    # STRING, ...) produces messages with those exact uppercase keys.
    raw = {
        "TRANSACTION_ID": "txn-1",
        "TERMINAL_ID": "TRM00001",
        "MERCHANT_ID": "MRC0001",
        "CARD_BIN": "539983",
        "FRAUD_PROBABILITY": 0.91,
        "ALERT_TIER": "critical",
        "STATE": "Lagos",
        "TERMINAL_NAME": "Ikeja Retail Counter 1",
        "MERCHANT_NAME": "Ikeja Fashion Emporium",
    }

    normalized = normalize_alert(raw)

    assert normalized["transaction_id"] == "txn-1"
    assert normalized["alert_tier"] == "critical"
    # Every column append_alert() actually writes must survive normalization.
    for col in COLUMNS:
        if col not in {"alert_id", "created_at"}:  # generated by append_alert itself
            assert col in normalized
